# Hardware offset in milliseconds for correcting capture latency.
hardwareOffsetMs: 20

# Time-turning offsets. All values are added to the incoming LTC time.
# These can be positive or negative.
timeturnerOffset:
  hours: 1
  minutes: 2
  seconds: 3
  frames: 4
  milliseconds: 5
defaultNudgeMs: 2
