# Hardware offset in milliseconds for correcting capture latency.
hardwareOffsetMs: 20

# Time-turning offsets. All values are added to the incoming LTC time.
# These can be positive or negative.
timeturnerOffset:
  hours: 0
  minutes: 0
  seconds: 0
  frames: 0
