[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
# Cargo configuration for cross-compiling to a 64-bit ARM Raspberry Pi.
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
